/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedPatientsIndexRouteImport } from './routes/_authed/patients/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedPatientsNewRouteImport } from './routes/_authed/patients/new'
import { Route as AuthedPatientsPatientIdIndexRouteImport } from './routes/_authed/patients/$patientId/index'
import { Route as AuthedOrdersOrderIdIndexRouteImport } from './routes/_authed/orders/$orderId/index'
import { Route as AuthedPatientsPatientIdEditRouteImport } from './routes/_authed/patients/$patientId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPatientsNewRoute = AuthedPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPatientsPatientIdIndexRoute =
  AuthedPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrdersOrderIdIndexRoute =
  AuthedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPatientsPatientIdEditRoute =
  AuthedPatientsPatientIdEditRouteImport.update({
    id: '/patients/$patientId/edit',
    path: '/patients/$patientId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthedIndexRoute
  '/patients/new': typeof AuthedPatientsNewRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/patients/$patientId/edit': typeof AuthedPatientsPatientIdEditRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdIndexRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthedIndexRoute
  '/patients/new': typeof AuthedPatientsNewRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/patients/$patientId/edit': typeof AuthedPatientsPatientIdEditRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdIndexRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/patients/new': typeof AuthedPatientsNewRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/patients/': typeof AuthedPatientsIndexRoute
  '/_authed/patients/$patientId/edit': typeof AuthedPatientsPatientIdEditRoute
  '/_authed/orders/$orderId/': typeof AuthedOrdersOrderIdIndexRoute
  '/_authed/patients/$patientId/': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/patients/new'
    | '/orders'
    | '/patients'
    | '/patients/$patientId/edit'
    | '/orders/$orderId'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/patients/new'
    | '/orders'
    | '/patients'
    | '/patients/$patientId/edit'
    | '/orders/$orderId'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/'
    | '/_authed/patients/new'
    | '/_authed/orders/'
    | '/_authed/patients/'
    | '/_authed/patients/$patientId/edit'
    | '/_authed/orders/$orderId/'
    | '/_authed/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/patients/': {
      id: '/_authed/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/patients/new': {
      id: '/_authed/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthedPatientsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/patients/$patientId/': {
      id: '/_authed/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$orderId/': {
      id: '/_authed/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/patients/$patientId/edit': {
      id: '/_authed/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof AuthedPatientsPatientIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPatientsNewRoute: typeof AuthedPatientsNewRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
  AuthedPatientsPatientIdEditRoute: typeof AuthedPatientsPatientIdEditRoute
  AuthedOrdersOrderIdIndexRoute: typeof AuthedOrdersOrderIdIndexRoute
  AuthedPatientsPatientIdIndexRoute: typeof AuthedPatientsPatientIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPatientsNewRoute: AuthedPatientsNewRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
  AuthedPatientsPatientIdEditRoute: AuthedPatientsPatientIdEditRoute,
  AuthedOrdersOrderIdIndexRoute: AuthedOrdersOrderIdIndexRoute,
  AuthedPatientsPatientIdIndexRoute: AuthedPatientsPatientIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
